spring.application.name=projectfoodspots
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.security.secret-key=EdofPsMCVjzhT7WmJgvaZiBH/ospf5MNvs0PNmJo2COYqTEoucZ4oRypqwlO5d+z
app.security.jwt-expiration=3600000

allowed.origins[0]=http://localhost:5173

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/${DB_NAME:foodspotsdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:userspots}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
